const POP_COLORS = ['#d8e8f0','#acd0df','#73b2c9','#3e8eae','#17678f'];
const BREAKS = { total:[1,150,350,600,900], young:[1,15,35,65,100], working:[1,80,190,340,500], senior:[1,60,130,210,300] };
const state = { data:null, map:null, layer:null, year:2025, metric:'total' };
const fmt = value => Math.round(value || 0).toLocaleString('ja-JP');
function color(value) { if (!value) return 'transparent'; const b=BREAKS[state.metric]; let i=0; while(i<b.length && value>=b[i]) i++; return POP_COLORS[Math.max(0,Math.min(i-1,POP_COLORS.length-1))]; }
function style(feature) { const value=feature.properties.values[String(state.year)][state.metric]||0; return { color:'rgba(255,255,255,.55)', weight:.35, fillColor:color(value), fillOpacity:value===0?0:.5 }; }
function popup(feature) { const v=feature.properties.values[String(state.year)]; const labels=state.data.meta.metrics; return `<div class="mn-popup"><strong>${state.year}年推計</strong><div class="mn-popup-tags"><span>${feature.properties.id}</span></div><ul><li>${labels.total}：${fmt(v.total)}人</li><li>${labels.young}：${fmt(v.young)}人</li><li>${labels.working}：${fmt(v.working)}人</li><li>${labels.senior}：${fmt(v.senior)}人</li></ul></div>`; }
function updateSummary(){ const s=state.data.meta.summaries[String(state.year)]; document.querySelector('#summaryYear').textContent=`${state.year}年`; for(const key of ['total','young','working','senior']) document.querySelector(`#sum-${key}`).textContent=`${fmt(s[key])}人`; }
function updateLegend(){ const root=document.querySelector('#populationLegend'); const b=BREAKS[state.metric]; const labels=['0（透明）',`${b[0]}～${b[1]-1}`,`${b[1]}～${b[2]-1}`,`${b[2]}～${b[3]-1}`,`${b[3]}～${b[4]-1}`,`${b[4]}以上`]; const swatches=['transparent',...POP_COLORS]; root.innerHTML=`<strong>${state.data.meta.metrics[state.metric]}（人／250mメッシュ）</strong>${labels.map((label,i)=>`<div class="mn-legend-row"><span class="mn-legend-swatch" style="background:${swatches[i]};${i===0?'border-style:dashed;':''}"></span>${label}</div>`).join('')}`; }
function render(){ state.layer.setStyle(style); state.layer.eachLayer(layer=>layer.setPopupContent(popup(layer.feature))); updateSummary(); updateLegend(); document.querySelector('#yearLabel').textContent=`${state.year}年`; }
function setMapAspect(bounds){ const west=bounds.getWest(), east=bounds.getEast(), south=bounds.getSouth(), north=bounds.getNorth(); const mid=(south+north)/2*Math.PI/180; const width=Math.max(.001,(east-west)*Math.cos(mid)); const height=Math.max(.001,north-south); const ratio=Math.max(.72,Math.min(1.65,width/height)); document.querySelector('#populationMap').style.aspectRatio=String(ratio); document.querySelector('#populationMap').style.height='auto'; document.querySelector('#populationMap').style.minHeight='420px'; }
async function init(){ const res=await fetch('content/population-outlook.geojson'); if(!res.ok) throw new Error('人口データを読み込めませんでした'); state.data=await res.json(); state.map=L.map('populationMap',{scrollWheelZoom:true}).setView([35.323,139.505],13); L.tileLayer('https://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png',{maxZoom:18,attribution:'<a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank" rel="noopener">地理院タイル</a>'}).addTo(state.map); state.layer=L.geoJSON(state.data,{style,onEachFeature:(f,l)=>l.bindPopup(popup(f),{maxWidth:280})}).addTo(state.map); const bounds=state.layer.getBounds(); setMapAspect(bounds); setTimeout(()=>{state.map.invalidateSize(); state.map.fitBounds(bounds,{padding:[8,8]});},0); const range=document.querySelector('#yearRange'); range.min=0; range.max=state.data.meta.years.length-1; range.value=0; range.addEventListener('input',()=>{state.year=state.data.meta.years[Number(range.value)];render();}); document.querySelectorAll('[data-metric]').forEach(button=>button.addEventListener('click',()=>{state.metric=button.dataset.metric;document.querySelectorAll('[data-metric]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));render();})); const legend=L.control({position:'bottomright'}); legend.onAdd=()=>{const div=L.DomUtil.create('div','mn-legend');div.id='populationLegend';return div;}; legend.addTo(state.map); render(); }
init().catch(error=>{document.querySelector('#populationMap').innerHTML=`<p class="mn-note">${error.message}。ローカルHTTPサーバーから開いてください。</p>`;});
