const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const SERVICE_COLORS={police:'#315e9b',fire:'#b65b55'};
const state={data:null,map:null,services:new Set(['police','fire']),areas:new Set(['police','fire']),markers:new Map(),areaLayers:new Map(),visible:[]};
const iconPaths={police:'<path d="M12 3 20 6v5c0 5-3 8-8 10-5-2-8-5-8-10V6Z"/><path d="M9 11h6M12 8v6"/>',fire:'<path d="M13 2c1 4-2 5 0 8 2-2 3-4 3-6 4 4 5 8 3 12-1 3-4 5-7 5-5 0-8-3-8-7 0-4 3-7 6-10 0 3 1 5 3 6"/>'};
function markerClass(item){if(item.facilityType.endsWith('Headquarters'))return'is-hq';if(item.facilityType.endsWith('Station'))return'is-station';return'is-post'}
function markerIcon(item){const size=item.facilityType.endsWith('Headquarters')?[34,38]:item.facilityType.endsWith('Station')?[29,29]:[23,23];const anchor=[Math.round(size[0]/2),size[1]];return L.divIcon({className:'safety-marker-shell',html:`<span class="safety-marker ${markerClass(item)} ${item.status?'is-closed':''}" style="--marker-color:${SERVICE_COLORS[item.service]}"><svg viewBox="0 0 24 24" aria-hidden="true">${iconPaths[item.service]}</svg></span>`,iconSize:size,iconAnchor:anchor,popupAnchor:[0,-size[1]+3]})}
function typeLabel(item){return({policeHeadquarters:'警察署',policeBox:'交番',residentialPost:'駐在所',fireHeadquarters:'消防本部',fireStation:'消防署',firePost:'出張所・分遣所'})[item.facilityType]||item.facilityType}
function popupHtml(item){return`<div class="mn-popup"><strong>${escapeHtml(item.name)}</strong><span class="mn-popup-address">${escapeHtml(item.address)}</span><div class="mn-popup-tags"><span>${escapeHtml(typeLabel(item))}</span></div>${item.status?`<span class="safety-status">${escapeHtml(item.status)}</span>`:''}${item.publicDescription?`<p>${escapeHtml(item.publicDescription)}</p>`:''}<p><a href="${escapeHtml(item.officialUrl)}" target="_blank" rel="noopener">公式情報 ↗</a></p></div>`}
function visibleFacilities(){return state.data.facilities.filter(item=>state.services.has(item.service))}
function renderFacilities(){state.markers.forEach(marker=>marker.remove());state.markers.clear();state.visible=visibleFacilities();for(const item of state.visible){const marker=L.marker([item.lat,item.lng],{icon:markerIcon(item),title:item.name,riseOnHover:true}).addTo(state.map).bindPopup(popupHtml(item),{maxWidth:320});state.markers.set(item.id,marker)}renderList()}
function areaStyle(feature){const service=feature.properties.service;return{color:SERVICE_COLORS[service],weight:1.15,opacity:.65,fillColor:SERVICE_COLORS[service],fillOpacity:.1}}
function renderAreas(){for(const [service,layer]of state.areaLayers){if(state.areas.has(service)){if(!state.map.hasLayer(layer))layer.addTo(state.map)}else if(state.map.hasLayer(layer))layer.remove()}}
function focusFacility(id){const item=state.visible.find(entry=>entry.id===id),marker=state.markers.get(id);if(!item||!marker)return;state.map.setView([item.lat,item.lng],Math.max(state.map.getZoom(),15));marker.openPopup()}
function renderList(){document.querySelector('#safetyCount').textContent=`${state.visible.length}施設`;const root=document.querySelector('#safetyList');root.innerHTML=[...state.visible].sort((a,b)=>a.name.localeCompare(b.name,'ja')).map(item=>`<article class="mn-place-item"><button type="button" data-safety-id="${escapeHtml(item.id)}"><small>${escapeHtml(typeLabel(item))}</small><strong>${escapeHtml(item.name)}</strong><span>${escapeHtml(item.address)}</span></button></article>`).join('');root.querySelectorAll('[data-safety-id]').forEach(button=>button.addEventListener('click',()=>focusFacility(button.dataset.safetyId)))}
function renderLegend(){document.querySelector('#safetyLegend').innerHTML=`<strong>施設</strong><div class="safety-legend-row"><i class="safety-legend-symbol police hq"></i>警察署</div><div class="safety-legend-row"><i class="safety-legend-symbol police post"></i>交番・駐在所</div><div class="safety-legend-row"><i class="safety-legend-symbol fire station"></i>消防本部・消防署</div><div class="safety-legend-row"><i class="safety-legend-symbol fire post"></i>出張所・分遣所</div><strong>区域</strong><div class="safety-legend-row"><i class="safety-legend-area police"></i>警察署管轄</div><div class="safety-legend-row"><i class="safety-legend-area fire"></i>消防署管轄</div>`}
function bindControls(){document.querySelectorAll('[data-service]').forEach(button=>button.addEventListener('click',()=>{const value=button.dataset.service;if(state.services.has(value)&&state.services.size>1)state.services.delete(value);else state.services.add(value);button.setAttribute('aria-pressed',String(state.services.has(value)));renderFacilities()}));document.querySelectorAll('[data-area]').forEach(button=>button.addEventListener('click',()=>{const value=button.dataset.area;if(state.areas.has(value))state.areas.delete(value);else state.areas.add(value);button.setAttribute('aria-pressed',String(state.areas.has(value)));renderAreas()}))}
async function init(){if(!window.L)throw new Error('地図ライブラリを読み込めませんでした');const response=await fetch('content/safety-map.json');if(!response.ok)throw new Error('消防・警察データを読み込めませんでした');state.data=await response.json();state.map=L.map('safetyMap',{scrollWheelZoom:true}).setView([35.331,139.506],12);L.tileLayer('https://cyberjapandata.gsi.go.jp/xyz/pale/{z}/{x}/{y}.png',{maxZoom:18,attribution:'<a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank" rel="noopener">地理院タイル</a>'}).addTo(state.map);L.control.scale({imperial:false,position:'bottomleft'}).addTo(state.map);for(const service of['police','fire']){const features=state.data.areas.features.filter(feature=>feature.properties.service===service);const layer=L.geoJSON({type:'FeatureCollection',features},{style:areaStyle,onEachFeature:(feature,itemLayer)=>itemLayer.bindPopup(`<div class="mn-popup"><strong>${escapeHtml(feature.properties.name)}</strong><p>${escapeHtml(feature.properties.sourceDataset)}（${feature.properties.sourceYear}年）</p></div>`)});state.areaLayers.set(service,layer);layer.addTo(state.map)}renderFacilities();renderLegend();bindControls();const panel=document.querySelector('#safetyListPanel'),toggle=document.querySelector('#toggleSafetyList');const setPanel=open=>{panel.hidden=!open;toggle.textContent=open?'施設一覧を閉じる':'施設一覧を開く';setTimeout(()=>state.map.invalidateSize(),0)};toggle.addEventListener('click',()=>setPanel(panel.hidden));if(matchMedia('(max-width:640px)').matches)setPanel(false)}
init().catch(error=>{document.querySelector('#safetyMap').innerHTML=`<p class="mn-note">${escapeHtml(error.message)}。データ生成とローカルHTTPサーバーを確認してください。</p>`})
